apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudml-agent
  namespace: cloudml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudml-agent-role
  namespace: cloudml
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["cloudml-agent-secret"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudml-agent-rolebinding
  namespace: cloudml
subjects:
- kind: ServiceAccount
  name: cloudml-agent
  namespace: cloudml
roleRef:
  kind: Role
  name: cloudml-agent-role
  apiGroup: rbac.authorization.k8s.io 