apiVersion: v1
kind: Service
metadata:
  name: cloudml-app-service
  namespace: cloudml
spec:
  type: LoadBalancer
  selector:
    app: cloudml-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudml-app-deployment
  namespace: cloudml
spec:
  strategy:
     rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      app: cloudml-app
  template:
    metadata:
      labels:
        app: cloudml-app
    spec:
      containers:
      - name: cloudml-app
        image: kamikux/cloudml-app:latest
        # health check
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 300
        # readiness probe
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        # port
        ports:
        - containerPort: 5000
        # assign resources
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "128Mi" 
