apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: cloudml
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      initContainers:
        - name: init-fluentd
          image: busybox
          command: ['/bin/sh', '-c', 'mkdir -p /var/log/td-agent/buffer/ /var/log/td-agent/buffer/cloudml/ /var/log/td-agent/buffer/general/']
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.18-debian-kafka2-1
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluentd-config
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluentd-config
          configMap:
            name: fluentd-config