apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: log-collectors
data:
  fluent.conf: |
    # Disable fluentd logs to avoid loops
    <label @FLUENT_LOG>
      <match **>
        @type null
      </match>
    </label>

    # CloudML app specific logs
    <source>
      @type tail
      path /var/log/containers/cloudml-app*.log
      pos_file /var/log/fluentd-cloudml.log.pos
      tag cloudml
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    # Log to both stdout and Kafka for debugging
    <match cloudml>
      @type copy
      <store>
        @type stdout
      </store>
      <store>
        @type kafka2
        
        # Basic kafka configuration - simplify to ensure it works
        brokers kafka-service.log-collectors.svc.cluster.local:9092
        topic cloudml-app-logs
        default_topic cloudml-app-logs
        
        # Message formatting
        <format>
          @type json
        </format>
        
        # Buffer configuration - minimal
        <buffer>
          @type memory
          flush_interval 1s
        </buffer>
      </store>
    </match> 